name: Eslint

on: [push]

jobs:
  build:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Eslint
        run: npm run eslint

