name: Unit Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Unit Test
        run: npm run test

