name: Unit Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Packages
        run: npm install
      - name: Unit Test
        run: npm run test:lib

